# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_bus.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'grpc_bus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpc_bus.proto\x12\x0bmeetmaxxing\"K\n\x0bTaskRequest\x12\x12\n\nagent_name\x18\x01 \x01(\t\x12\x12\n\nmeeting_id\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\"K\n\x0cTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2S\n\x0c\x41gentTaskBus\x12\x43\n\x0c\x44ispatchTask\x12\x18.meetmaxxing.TaskRequest\x1a\x19.meetmaxxing.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_bus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=31
  _globals['_TASKREQUEST']._serialized_end=106
  _globals['_TASKRESPONSE']._serialized_start=108
  _globals['_TASKRESPONSE']._serialized_end=183
  _globals['_AGENTTASKBUS']._serialized_start=185
  _globals['_AGENTTASKBUS']._serialized_end=268
# @@protoc_insertion_point(module_scope)
